### ISSUE TITLE
Cannot find type definition file

### ISSUE THREAD

**Issue by KTibow** [Maxssho13/CTAutocomplete#7]
This is probably more of a VS code issue, but here seems like the best place to ask.

I installed this module and it works just fine for metadata.json. However, in my JS file, it gives me the error
```
Cannot find type definition file for '/home/kendell/.minecraft/config/chattriggers/modules/ctautocomplete'.ts(2688)
```
I checked and the directory is there. Any idea how to fix this issue?

**Comment by glasss13** [comment]
Can you show how you are trying to include the type definitions?

**Comment by KTibow** [comment]
```js
/// <reference types="/home/kendell/.minecraft/config/ChatTriggers/modules/CTAutocomplete" />
/// <reference lib="es2015" />
// BetterChat: A better chat experience on Hypixel.
// Version 1.1.0, for ChatTriggers.js, by KTibow#3960.

// ect ect
```

**Comment by glasss13** [comment]
Refer to the instructions in the Readme

**Comment by KTibow** [comment]
I did originally, it gave the same error. I checked absolute paths, those didn't work either. And it's not ASM.

**Comment by glasss13** [comment]
I would just make sure its the correct path.

**Comment by KTibow** [comment]
I did. I copied the exact file path into the terminal and it opened just fine.

**Comment by glasss13** [comment]
maybe try:
`
/// <reference path="path/to/index.d.ts" />
`

**Comment by KTibow** [comment]
Also tried copying that exact path, didn't work.

**Comment by glasss13** [comment]
you copy and pasted that line exactly or you put in your own, correct path?

**Comment by KTibow** [comment]
Sorry for the confusing comment. I tried using index.d.ts, it didn't work. To make sure it was correct, I copied it, and pasted it into an editor, which opened successfully. Same error:
![image](https://user-images.githubusercontent.com/10727862/143511444-cfdb892e-9e6b-4ab0-aa26-3778287ec787.png)

**Comment by glasss13** [comment]
reference path, not types

**Comment by KTibow** [comment]
wdym?

**Comment by KTibow** [comment]
this also doesn't work
![image](https://user-images.githubusercontent.com/10727862/143511567-bd08a1fd-ba14-4e66-99be-d17a7ae5b4b5.png)

**Comment by glasss13** [comment]
> maybe try: `/// <reference path="path/to/index.d.ts" />`

**Comment by KTibow** [comment]
oh i didn't see that bit
but it works now!
thx!

**Comment by KTibow** [comment]
(didn't close earlier because internet was down)
